server:
  port: 5001
spring:
  application:
    # 应用名称
    name: to-collect-fund
  cloud:
    nacos:
      discovery:
        # Nacos 服务发现与注册配置，其中子属性 server-addr 指定 Nacos 服务器主机和端口
        server-addr: 127.0.0.1:8848
        # 注册到 nacos 的指定 namespace，默认为 public
  #        namespace: public
  #        # Nacos认证信息
  #        # password: nacos
  #        # username: nacos
  #        group: fund-store
  kafka:
    bootstrap-servers: 106.12.162.149:9092,106.12.162.149:9093,106.12.162.149:9094
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      batch-size: 16384 # 每次批量发送消息的最大数量
      buffer-memory: 33554432 # 每次批量发送消息的最大内存
      properties:
        linger:
          ms: 10000 # 批处理延迟时间上限。这里配置为 10 * 1000 ms 过后，不管是否消息数量是否到达 batch-size
  # 对应 RedisProperties 类
  redis:
    redisson:
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          address: redis://127.0.0.1:6379
          password: 
          clientName: null
          keepAlive: false
          tcpNoDelay: false
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
        transportMode: "NIO"
# 全局配置下，所有请求的默认重试信息按此配置进行
forest:
  # 配置后端HTTP API为 okhttp3
  backend: okhttp3
  # 最大请求重试次数，默认为 0 次
  max-retry-count: 30000
  # 为最大重试时间间隔, 单位为毫秒，默认为 0 毫秒
  max-retry-interval: 10
  ## 日志总开关，打开/关闭Forest请求/响应日志（默认为 true）
  log-enabled: false
  ## 打开/关闭Forest请求日志（默认为 true）
  log-request: true
  ## 打开/关闭Forest响应状态日志（默认为 true）
  log-response-status: true
  ## 打开/关闭Forest响应内容日志（默认为 false）
  log-response-content: true
  # 转换器配置，支持 json, xml, text, binary 四种数据类型的配置
  converters:
    # JSON转换器
    json:
      # JSON转换器设置为GSON转换器
      type: com.fund.collect.convert.CustomForestJsonConverter
      # 转换器的参数设置
      parameters:
        # JSON数据转换器的全局日期格式化配置
        dateFormat: yyyy-MM-dd
liteflow:
  ruleSource: liteflow/*/*.xml
  enable: false

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:6080/xxl-job-admin
    accessToken: default_token
    executor:
      appname: to-collect-fund
      address: http://192.168.0.121:9999
      ip: 192.168.0.199
      port: 9999
      logpath: D:\\new\\xxl-job\\log
      logretentiondays: 30
